### PR TITLE
strict parsing a date in dayjs by default

### PR DESCRIPTION
**Pull request by hamcher**
Hi, we found a problem when we using AdapterDayjs with mui date picker in the validation

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
How this will imply on the previous working examples? We must be backward compatible

**Comment by chwallen** [comment]
> How this will imply on the previous working examples? We must be backward compatible

It will be a breaking change I guess as without strict parsing, `dayjs` will consider invalid dates to be valid.
For example, `03/13/2021` (as DD/MM/YYYY, but the same will apply to any other format) without strict mode will parse as `03/01/2022`, wrapping the months. Another example is that `87/65/4321` parses as the ISO string `1238-10-16T22:47:48.000Z`. With strict mode, both of these will return an `Invalid Date`, which is more logical and more likely what is expected.

This is documented on the website:
<https://day.js.org/docs/en/parse/string-format>

**Comment by dmtrKovalenko** [comment]
The biggest question from me – will it require breaking change? If not - I will be happy to merge it and release right now

**Comment by chwallen** [comment]
> The biggest question from me – will it require breaking change? If not - I will be happy to merge it and release right now

I cannot answer more than I did above. Without strict mode, `dayjs` will turn invalid dates valid. With it, invalid dates will be returned as invalid.  If you consider this breaking, then sure.

**Comment by kjellski** [comment]
Can you guys merge either #599  OR #608  ? Changes are equal... but the fix would be great... :grimacing: @dmtrKovalenko

**Comment by kjellski** [comment]
As the other PR was merged, this can be closed :)

**Pull request closed without merging**
