### PR TITLE
Separate dev dependencies.

### PR DESCRIPTION
**Pull request by deluksic**
#134

### CODE REVIEW

**Comment by deluksic** [comment]
I'm not sure how versioning works if you don't change anything regarding functionality, so help here is appreciated.

**Comment by dmtrKovalenko** [comment]
Thanks. But you have edited the root package.json. But for date-fns submodule it will be `packages/date-fans/package.json`

**Comment by deluksic** [comment]
Hmm, looking at `date-fns/package.json` I don't see anything wrong with it. The original problem is with the root level `package.json`, I think.

**Comment by dmtrKovalenko** [comment]
Yeah but it is not using for packages. All package.json for libs are inside the packages/*

**Comment by deluksic** [comment]
In any case, these dependencies should be in `devDependencies` don't you agree? Also, if only these are used, how come the graph for [@date-io/date-fns](http://npm.broofa.com/?q=@date-io/date-fns) shows a huge tree?

**Comment by deluksic** [comment]
Also [npms.io confirms these dependencies](https://api.npms.io/v2/package/%40date-io%2Fdate-fns)

**Comment by TrySound** [comment]
See comment in issue

**Pull request closed without merging**
