### PR TITLE
getMeridiemText() from moment utils now returns translated text

### PR DESCRIPTION
**Pull request by ScripterSugar**
#473

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Thank you so much! If you don't mind can you also add a couple of tests to `localization.test.ts ` file?

**Review by dmtrKovalenko — APPROVED** [review]
Awesome, thank you!

**Comment by dmtrKovalenko** [comment]
Oops, CI failed 😖

**Comment by ScripterSugar** [comment]
Working for it RN, I'm not quite used to those tests LoL Sorry

**Comment by dmtrKovalenko** [comment]
No worries. I can take a look on failures if you won't resolve the problem. But in a few hours :)

**Comment by ScripterSugar** [comment]
Now it looks got to me. :)

**Review by dmtrKovalenko — APPROVED** [review]

**Pull request merged**
