### PR TITLE
feat: js-joda support

### PR DESCRIPTION
**Pull request by dspiteself**
All tests pass and it seems to be working well from mui datepicker.

### CODE REVIEW

**Comment by dspiteself** [comment]
> Please make sure that coverage remains 100%

The Coverage should be back up. How to I get Codecov to rerun on the PR. I had to add a test file for the LocalDate specific type. That my not be the way you want to go. I could have 'parse' and 'date' always return LocalDateTime and just have date allow other TemporalTypes to be passed through.

**Comment by dmtrKovalenko** [comment]
It should automatically run on CI

**Comment by dmtrKovalenko** [comment]
Looks like CI is not happy, I will get back to your PR tomorrow

**Comment by dspiteself** [comment]
Maybe it was me adding the dependency on  
`"cldr-data" : "^36.0.0",
 "cldrjs" : "^0.5.5"`
 for the outer project

**Pull request merged**
